spring:
  redis:
    lettuce:
      pool:
        max-active: 10 # pool에 할당될 수 있는 커넥션 최대수
        max-idle: 10 # pool의 'idle' 커넥션 최대수
        min-idle: 2
    host: 127.0.0.1
    port: 6379

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true


